[theme]
base="light"
primaryColor="#2E7D32"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#FFFFFF"
<<<<<<< HEAD
textColor="#000000"
=======
textColor="#000000"
>>>>>>> c104437 ( Process update including a secure password over the code to secure the file)
